<a href="https://colab.research.google.com/github/ayush572/Final_Year_Internship_Work/blob/main/Description_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!unzip /content/drive/MyDrive/description_dataset/Book_description_92000.zip

Streaming output truncated to the last 5000 lines.
  inflating: Book_description_All/89588.txt  
  inflating: Book_description_All/895895.txt  
  inflating: Book_description_All/89590.txt  
 extracting: Book_description_All/89591445.txt  
  inflating: Book_description_All/895936.txt  
  inflating: Book_description_All/896.txt  
  inflating: Book_description_All/89601.txt  
  inflating: Book_description_All/896026.txt  
  inflating: Book_description_All/896054.txt  
  inflating: Book_description_All/89612.txt  
  inflating: Book_description_All/896121.txt  
  inflating: Book_description_All/896144.txt  
  inflating: Book_description_All/896224.txt  
  inflating: Book_description_All/896231.txt  
  inflating: Book_description_All/896235.txt  
  inflating: Book_description_All/89626.txt  
  inflating: Book_description_All/896265.txt  
  inflating: Book_description_All/896268.txt  
  inflating: Book_description_All/89628.txt  
  inflating: Book_description_All/896295.txt  
  inflating: Boo

In [ ]:

import pandas as pd

# Replace 'path/to/your/csv/file.csv' with the actual path to your CSV file
output_csv = '/content/drive/MyDrive/description_dataset/output.csv'

# Load the CSV file into a pandas DataFrame
df = pd.read_csv(output_csv)

# Display the first few rows of the DataFrame
df.head()

ISBN-13  Fiction/Non-fiction  \
0  9780195153446           Nonfiction   
1  9780002005012              Fiction   
2  9780060973124  Nonfiction, Fiction   
3  9780374157067           Nonfiction   
4  9780393045215           Nonfiction   

                                          Categories  \
0  Mythology, History, Reference, Religion & Spir...   
1    Historical, Literature, Comics & Graphic Novels   
2                                            History   
3  History, Politics & Social Sciences, Science &...   
4                                            History   

                              First Three Categories  \
0                       Mythology, History, Classics   
1       Canada, Historical Fiction, Literary Fiction   
2  History, World War IINonfiction, Military History   
3                          History, Science, Medical   
4                        History, Archaeology, China   

                       Remaining Categories  
0           Reference, Textbooks, Religion   
1  Canadian Literature, Novels, Historical   
2     War, Military Fiction, World History   
3                Medicine, Health, Disease   
4      Anthropology, Asia, Ancient History

In [ ]:
len(df)

10218

In [ ]:
import pandas as pd

dataset_csv = '/content/drive/MyDrive/description_dataset/Final_consolidate_file_for_First_10000.csv'

# Load the CSV file into a pandas DataFrame
df_dataset_csv = pd.read_csv(dataset_csv)

# Display the first few rows of the DataFrame
df_dataset_csv.head()


ISBN-13                                             Genres  \
0  9780195153446  Mythology, Nonfiction, History, Classics, Refe...   
1  9780002005012  Fiction, Canada, Historical Fiction, Literary ...   
2  9780060973124  History, World War IINonfiction, Military Hist...   
3  9780374157067  History, Nonfiction, Science, Medical, Medicin...   
4  9780393045215  History, Archaeology, Nonfiction, China, Anthr...   

      Coverpage   Description  
0    846427.jpg    846427.txt  
1    969335.jpg    969335.txt  
2  no-cover.png  no-cover.txt  
3    893390.jpg    893390.txt  
4   1357556.jpg   1357556.txt

In [ ]:
import os
description_data = '/content/Book_description_All'
all_files = os.listdir(description_data)
flag = 0
for idx, file in enumerate(all_files):
  if file == 'no-cover.txt':
    print(idx)
    flag = 1
if flag == 0:
  print('no such file')

31296


In [ ]:
len(all_files)

92677

In [ ]:
# Create a new DataFrame with only the rows where non-NaN, and data entry is either 'Fiction' or 'Non-Fiction' but not both
df = df[df['Fiction/Non-fiction'].apply(lambda x: isinstance(x, str) and x in ['Fiction', 'Nonfiction'])].copy()

# Resetting index of new dataframe
df.reset_index(drop=True, inplace=True)

df

ISBN-13 Fiction/Non-fiction  \
0     9780195153446          Nonfiction   
1     9780002005012             Fiction   
2     9780374157067          Nonfiction   
3     9780393045215          Nonfiction   
4     9780399135781             Fiction   
...             ...                 ...   
7181  9780590406543             Fiction   
7182  9780749707934             Fiction   
7183  9780517189672             Fiction   
7184  9780810943988             Fiction   
7185  9780749712297             Fiction   

                                             Categories  \
0     Mythology, History, Reference, Religion & Spir...   
1       Historical, Literature, Comics & Graphic Novels   
2     History, Politics & Social Sciences, Science &...   
3                                               History   
4                                Historical, Literature   
...                                                 ...   
7181              Science & Fantasy, Teen & Young Adult   
7182              Science & Fantasy, Travel, Historical   
7183                     Teen & Young Adult, Historical   
7184                                                NaN   
7185                     Literature, Teen & Young Adult   

                            First Three Categories  \
0                     Mythology, History, Classics   
1     Canada, Historical Fiction, Literary Fiction   
2                        History, Science, Medical   
3                      History, Archaeology, China   
4                  Historical Fiction, China, Asia   
...                                            ...   
7181             Fantasy, Childrens, Chapter Books   
7182              Fantasy, Childrens, Middle Grade   
7183              Classics, Childrens, Young Adult   
7184              Picture Books, Childrens, France   
7185                      Animals, Childrens, Cats   

                               Remaining Categories  
0                   Reference, Textbooks, Religion   
1          Canadian Literature, Novels, Historical   
2                        Medicine, Health, Disease   
3              Anthropology, Asia, Ancient History   
4       Contemporary, Asian Literature, Historical   
...                                             ...  
7181                                    Young Adult  
7182     Time Travel, Historical Fiction, Medieval   
7183  Historical Fiction, Middle Grade, Historical   
7184                             Halloween, Animals  
7185     Adventure, British Literature, Young Adult  

[7186 rows x 5 columns]

In [ ]:
all_desc_txt = df_dataset_csv['Description'].tolist()
len(all_desc_txt)

10272

In [ ]:
# means if for a particular file name, that file doesn't exists
count = 0
for idx, data in enumerate(all_desc_txt): # this is just the text from csv file
  flag = 0
  for index, file in enumerate(all_files): # all_files variable, in actual, have all the text files

  # means for the particular data, that file exists
    if data == file:
      flag = 1
      break
  if flag == 0:
    print('idx:', idx, ' and data:', data)
    # Remove the corresponding row from df_dataset_csv
    df_dataset_csv = df_dataset_csv.drop(idx, axis=0)
    count += 1

# Reset the index after removing rows
df_dataset_csv.reset_index(drop=True, inplace=True)
print('total such books:', count)

idx: 208  and data: 87950.txt
idx: 408  and data: .txt
idx: 409  and data: .txt
idx: 420  and data: .txt
idx: 525  and data: .txt
idx: 640  and data: 77473.txt
idx: 711  and data: 1514059.txt
idx: 771  and data: .txt
idx: 796  and data: .txt
idx: 970  and data: .txt
idx: 990  and data: 3912516.txt
idx: 1031  and data: 481372.txt
idx: 1038  and data: 77470.txt
idx: 1039  and data: .txt
idx: 1208  and data: .txt
idx: 1728  and data: .txt
idx: 1813  and data: .txt
idx: 1881  and data: .txt
idx: 1955  and data: .txt
idx: 1971  and data: .txt
idx: 2490  and data: 345061.txt
idx: 2618  and data: 163767.jpg
idx: 2647  and data: 355727.txt
idx: 2804  and data: 1037575.txt
idx: 2979  and data: 168642.txt
idx: 3142  and data: .txt
idx: 3163  and data: .txt
idx: 3273  and data: 371918.txt
idx: 3274  and data: 105806.txt
idx: 3288  and data: .txt
idx: 3337  and data: 28103696.txt
idx: 3646  and data: 93941.txt
idx: 3701  and data: 1791619.txt
idx: 3817  and data: .txt
idx: 3902  and data: .txt
idx

In [ ]:
# data after cleansing
all_desc_txt = df_dataset_csv['Description'].tolist()
len(all_desc_txt)

10180

In [ ]:
df_dataset_csv.head()

ISBN-13                                             Genres  \
0  9780195153446  Mythology, Nonfiction, History, Classics, Refe...   
1  9780002005012  Fiction, Canada, Historical Fiction, Literary ...   
2  9780060973124  History, World War IINonfiction, Military Hist...   
3  9780374157067  History, Nonfiction, Science, Medical, Medicin...   
4  9780393045215  History, Archaeology, Nonfiction, China, Anthr...   

      Coverpage   Description  
0    846427.jpg    846427.txt  
1    969335.jpg    969335.txt  
2  no-cover.png  no-cover.txt  
3    893390.jpg    893390.txt  
4   1357556.jpg   1357556.txt

In [ ]:
desc = df_dataset_csv['Description']
desc = desc.tolist()
desc

['846427.txt',
 '969335.txt',
 'no-cover.txt',
 '893390.txt',
 '1357556.txt',
 '863993.txt',
 '406281.txt',
 '6262757.txt',
 '817876.txt',
 '260487.txt',
 '1425485.txt',
 '1272497.txt',
 '9675352.txt',
 '1055049.txt',
 '3085573.txt',
 '232142.txt',
 '1255282.txt',
 '5348.txt',
 '415907.txt',
 '579696.txt',
 '1035809.txt',
 '302816.txt',
 '1377348.txt',
 '2587531.txt',
 '667806.txt',
 '424442.txt',
 '760469.txt',
 '513625.txt',
 '497114.txt',
 '92488.txt',
 '713928.txt',
 '3342378.txt',
 'no-cover.txt',
 '1431947.txt',
 '9521920.txt',
 '899429.txt',
 '25587975.txt',
 '944288.txt',
 '830664.txt',
 '508571.txt',
 '937344.txt',
 '494448.txt',
 '104225.txt',
 '32426.txt',
 '43352.txt',
 '65948.txt',
 '320179.txt',
 '762550.txt',
 '34305.txt',
 '1418650.txt',
 '27523.txt',
 '87964.txt',
 '206125.txt',
 '915850.txt',
 'no-cover.txt',
 '988507.txt',
 '666006.txt',
 'no-cover.txt',
 '14978599.txt',
 '920643.txt',
 '836798.txt',
 '219570.txt',
 '1768188.txt',
 '947861.txt',
 'no-cover.txt',
 '10

In [ ]:
# removing those rows where no-cover.txt is written
count = 0
for idx, data in enumerate(df_dataset_csv['Description']): # this is just the text from csv file
  if data == 'no-cover.txt':
    # Remove the corresponding row from df_dataset_csv
    df_dataset_csv = df_dataset_csv.drop(idx, axis=0)
    count += 1

# Reset the index after removing rows
df_dataset_csv.reset_index(drop=True, inplace=True)
print('total such books:', count)

total such books: 223


In [ ]:
# just to confirm that all the no-cover.txt has been removed
desc = df_dataset_csv['Description']
desc = desc.tolist()
count = 0
for data in desc:
  if data == 'no-cover.txt':
    count += 1
count

0

In [ ]:
# now working on merging the data, one from the fiction/non-fiction cleansing and another from df_dataset_csv cleansing
# Replace 'ISBN-13' with the actual column name in your DataFrames
common_isbn_df = pd.merge(df, df_dataset_csv, on='ISBN-13', how='inner')

# common_isbn_df now contains only the rows with common 'ISBN-13' values
common_isbn_df

ISBN-13 Fiction/Non-fiction  \
0     9780195153446          Nonfiction   
1     9780002005012             Fiction   
2     9780374157067          Nonfiction   
3     9780393045215          Nonfiction   
4     9780399135781             Fiction   
...             ...                 ...   
7220  9780590406543             Fiction   
7221  9780749707934             Fiction   
7222  9780517189672             Fiction   
7223  9780810943988             Fiction   
7224  9780749712297             Fiction   

                                             Categories  \
0     Mythology, History, Reference, Religion & Spir...   
1       Historical, Literature, Comics & Graphic Novels   
2     History, Politics & Social Sciences, Science &...   
3                                               History   
4                                Historical, Literature   
...                                                 ...   
7220              Science & Fantasy, Teen & Young Adult   
7221              Science & Fantasy, Travel, Historical   
7222                     Teen & Young Adult, Historical   
7223                                                NaN   
7224                     Literature, Teen & Young Adult   

                            First Three Categories  \
0                     Mythology, History, Classics   
1     Canada, Historical Fiction, Literary Fiction   
2                        History, Science, Medical   
3                      History, Archaeology, China   
4                  Historical Fiction, China, Asia   
...                                            ...   
7220             Fantasy, Childrens, Chapter Books   
7221              Fantasy, Childrens, Middle Grade   
7222              Classics, Childrens, Young Adult   
7223              Picture Books, Childrens, France   
7224                      Animals, Childrens, Cats   

                               Remaining Categories  \
0                   Reference, Textbooks, Religion    
1          Canadian Literature, Novels, Historical    
2                        Medicine, Health, Disease    
3              Anthropology, Asia, Ancient History    
4       Contemporary, Asian Literature, Historical    
...                                             ...   
7220                                    Young Adult   
7221     Time Travel, Historical Fiction, Medieval    
7222  Historical Fiction, Middle Grade, Historical    
7223                             Halloween, Animals   
7224     Adventure, British Literature, Young Adult   

                                                 Genres    Coverpage  \
0     Mythology, Nonfiction, History, Classics, Refe...   846427.jpg   
1     Fiction, Canada, Historical Fiction, Literary ...   969335.jpg   
2     History, Nonfiction, Science, Medical, Medicin...   893390.jpg   
3     History, Archaeology, Nonfiction, China, Anthr...  1357556.jpg   
4     Fiction, Historical Fiction, China, Asia, Cont...   863993.jpg   
...                                                 ...          ...   
7220  Fantasy, Childrens, Fiction, Chapter Books, Yo...  2399077.jpg   
7221  Fiction, Fantasy, Childrens, Middle Grade, Tim...   472429.jpg   
7222  Classics, Fiction, Childrens, Young Adult, His...   852724.jpg   
7223  Picture Books, Childrens, Fiction, France, Hal...   630544.jpg   
7224  Animals, Childrens, Fiction, Cats, Adventure, ...  7152543.jpg   

      Description  
0      846427.txt  
1      969335.txt  
2      893390.txt  
3     1357556.txt  
4      863993.txt  
...           ...  
7220  2399077.txt  
7221   472429.txt  
7222   852724.txt  
7223   630544.txt  
7224  7152543.txt  

[7225 rows x 8 columns]

In [ ]:
# just checking if any row was empty
for idx, data in enumerate(all_desc_txt): # this is just the text from csv file
  flag = 0
  if pd.isna(data):
    print('idx:', idx,' and data:', data)

In [ ]:
!pip install chardet

In [ ]:
description_data

'/content/Book_description_All'

In [ ]:
# data in the no-cover.txt

file_path = os.path.join(description_data, '25.txt')

# Open and read the contents of the file
with open(file_path, 'r', encoding='utf-8') as file:
    file_contents = file.read()
    print(file_contents)




In [ ]:
description_data

'/content/Book_description_All'

In [ ]:
import os
import chardet

file_path = os.path.join(description_data, '25.txt')

# Detect the encoding of the file
with open(file_path, 'rb') as rawfile:
    result = chardet.detect(rawfile.read())

# Open and read the contents of the file with different encodings
try:
    with open(file_path, 'r', encoding=result['encoding']) as file:
        file_contents = file.read()
        print(file_contents)
except UnicodeDecodeError:
    print(f"Could not decode using {result['encoding']}. Trying different encodings.")




In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
# Dataset preprocessing
from nltk.stem.porter import PorterStemmer # for stemming
ps = PorterStemmer()
corpus = []
try_encodings = ['utf-8', 'latin-1', 'iso-8859-1', 'cp1252']
# try_encodings = ['utf-8']
# Download stopwords for both English and Spanish
stopwords_english = set(stopwords.words('english'))
# stopwords_spanish = set(stopwords.words('spanish'))

# Combine the stopwords lists
# stopwords_combined = stopwords_english.union(stopwords_spanish)

for i in range(len(common_isbn_df)): # len(common_isbn_df) -> length of merged doc
  file_path = os.path.join(description_data, common_isbn_df['Description'][i])
  # print(i)
  # Open the file in read and write mode
  for encoding in try_encodings:
    try:
        with open(file_path, 'r+', encoding=encoding) as file:
            file_contents = file.read() # reading contents of file
        break
    except UnicodeDecodeError:
        continue
  review = re.sub('[^a-zA-Z]', ' ', file_contents) # means, replacing all the characters, apart from a-z and A-Z, with '' blank space
  review = review.lower()
  review = review.split() # splitting - default delimiter white space
  # now review will be having the list of words insisde that specific sentence

  stemmed_words = []
  for word in review:
    if word not in stopwords_english:
      word = ps.stem(word)
      stemmed_words.append(word)
  review = stemmed_words
  review = ' '.join(review)
  corpus.append(review)

In [ ]:
corpus

['',
 '',
 '',
 '',
 'winni helen kept other worst secret fifti year believ die helen want expos everyth winni angrili determin must one tell daughter pearl past includ terribl truth even helen know begin winni stori life small island outsid shanghai place china world war ii trace happi desper event led winni come america',
 'former cop attorney fall danger tri find fellow attorney abscond million settlement fund cassett',
 'rous revisionist histori former head exhibit england nation maritim museum comb origin document record produc authorit definit account piraci golden age explod mani accept myth e walk plank pure fiction cordingli replac truth complex often bloodier pp photo map',
 'hail washington post book world one era vital master short form ann beatti offer reader unforgett glimps peopl come term world around charact find grew meet twenti thirti embodi curiou yet familiar fusion hope despair fine craft often surpris narr beatti write women nurs broken heart men look love marri 

In [ ]:
# now for those content where corpus == '', means that data is not readable or is an empty one, and hence we are removing those entries from the same
count = 0
for i in range(len(corpus)):
    if corpus[i] == '':
        count += 1
        print('index:', i)
        common_isbn_df.drop(i, axis=0, inplace=True)

common_isbn_df.reset_index(drop=True, inplace=True)
print(len(common_isbn_df))

index: 0
index: 1
index: 2
index: 3
index: 8
index: 9
index: 12
index: 13
index: 20
index: 23
index: 26
index: 28
index: 29
index: 35
index: 37
index: 38
index: 46
index: 52
index: 53
index: 57
index: 58
index: 59
index: 63
index: 64
index: 65
index: 68
index: 72
index: 73
index: 74
index: 75
index: 77
index: 78
index: 80
index: 81
index: 82
index: 85
index: 94
index: 95
index: 96
index: 97
index: 100
index: 101
index: 103
index: 104
index: 105
index: 108
index: 110
index: 111
index: 113
index: 115
index: 116
index: 120
index: 121
index: 122
index: 126
index: 128
index: 132
index: 134
index: 136
index: 137
index: 138
index: 139
index: 143
index: 145
index: 147
index: 156
index: 157
index: 160
index: 161
index: 164
index: 166
index: 167
index: 168
index: 169
index: 172
index: 173
index: 176
index: 177
index: 180
index: 181
index: 184
index: 185
index: 186
index: 187
index: 188
index: 189
index: 192
index: 196
index: 197
index: 198
index: 199
index: 200
index: 201
index: 202
index: 203
i

In [ ]:

for index, row in common_isbn_df.iterrows():
  print(row)


Streaming output truncated to the last 5000 lines.
Remaining Categories        Terrorism, Political Science, American History 
Genres                    History, Nonfiction, Politics, War, Terrorism,...
Coverpage                                                        215344.jpg
Description                                                      215344.txt
Name: 6669, dtype: object
ISBN-13                                                       9781583224939
Fiction/Non-fiction                                              Nonfiction
Categories                History, Politics & Social Sciences, Science &...
First Three Categories                               History, Politics, War
Remaining Categories        Terrorism, Political Science, American History 
Genres                    History, Nonfiction, Politics, War, Terrorism,...
Coverpage                                                        215344.jpg
Description                                                      215344.txt
Name: 6670,

In [ ]:
# removed those rows as well that had text files, but as it was unable to get read so removed them

print(len(common_isbn_df))

4277


In [ ]:
corpus = [sentence for sentence in corpus if sentence != '']

In [ ]:
len(corpus)

4277

In [ ]:
# Bag of Words Word Embedding

from sklearn.feature_extraction.text import CountVectorizer

# Create the CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the corpus into a bag-of-words matrix
X = vectorizer.fit_transform(corpus)

# Get the feature names (words)
feature_names = vectorizer.get_feature_names_out()

# Convert the bag-of-words matrix to a dense array and print the result
dense_array = X.toarray()
print(dense_array)

# Print the feature names (words)
print("Feature names:", feature_names)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Feature names: ['aa' 'aaaaaaaaaaaaaa' 'aab' ... 'zzqm' 'zzrnia' 'zzt']


In [ ]:
# Convert the bag-of-words matrix to a DataFrame
df = pd.DataFrame(dense_array, columns=feature_names)

# Print the DataFrame
print(df)

      aa  aaaaaaaaaaaaaa  aab  aag  aahz  aai  aakh  aan  aap  aaqx  ...  zxz  \
0      0               0    0    0     0    0     0    0    0     0  ...    0   
1      0               0    0    0     0    0     0    0    0     0  ...    0   
2      0               0    0    0     0    0     0    0    0     0  ...    0   
3      0               0    0    0     0    0     0    0    0     0  ...    0   
4      0               0    0    0     0    0     0    0    0     0  ...    0   
...   ..             ...  ...  ...   ...  ...   ...  ...  ...   ...  ...  ...   
4272   0               0    0    0     0    0     0    0    0     0  ...    0   
4273   0               0    0    0     0    0     0    0    0     0  ...    0   
4274   0               0    0    0     0    0     0    0    0     0  ...    0   
4275   0               0    0    0     0    0     0    0    0     0  ...    0   
4276   0               0    0    0     0    0     0    0    0     0  ...    0   

      zy  zyb  zyy  zz  zza

In [ ]:
X

<4277x23927 sparse matrix of type '<class 'numpy.int64'>'
	with 145628 stored elements in Compressed Sparse Row format>

In [ ]:
# Filter rows where at least one entry is not 0
non_zero_rows = df[(df != 0).any(axis=1)]

# Filter columns where at least one entry is not 0
non_zero_columns = df.loc[:, (df != 0).any(axis=0)]

# Display the filtered rows
print("Rows where at least one entry is not 0:")
print(non_zero_rows)

# Display the filtered columns
print("\nColumns where at least one entry is not 0:")
print(non_zero_columns)

Rows where at least one entry is not 0:
      aa  aaaaaaaaaaaaaa  aab  aag  aahz  aai  aakh  aan  aap  aaqx  ...  zxz  \
0      0               0    0    0     0    0     0    0    0     0  ...    0   
1      0               0    0    0     0    0     0    0    0     0  ...    0   
2      0               0    0    0     0    0     0    0    0     0  ...    0   
3      0               0    0    0     0    0     0    0    0     0  ...    0   
4      0               0    0    0     0    0     0    0    0     0  ...    0   
...   ..             ...  ...  ...   ...  ...   ...  ...  ...   ...  ...  ...   
4272   0               0    0    0     0    0     0    0    0     0  ...    0   
4273   0               0    0    0     0    0     0    0    0     0  ...    0   
4274   0               0    0    0     0    0     0    0    0     0  ...    0   
4275   0               0    0    0     0    0     0    0    0     0  ...    0   
4276   0               0    0    0     0    0     0    0    0     0  

In [ ]:
labels = common_isbn_df['Fiction/Non-fiction']
labels=labels.tolist()

Logistic Regression Method

In [ ]:
# logistic regression implemented with accuracy of 85% with BOG vectorization method

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
labels = common_isbn_df['Fiction/Non-fiction']
labels=labels.tolist()
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(dense_array, labels, test_size=0.33, random_state=42)

# Create a logistic regression model
model = LogisticRegression(class_weight = 'balanced')

# Train the model on the training data
model.fit(X_train, y_train)

# Make predictions on the test data
predictions = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, predictions)
conf_matrix = confusion_matrix(y_test, predictions)
classification_rep = classification_report(y_test, predictions)

# Display the results
print("Accuracy:", accuracy)
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)

Accuracy: 0.8505665722379604

Confusion Matrix:
[[1019   95]
 [ 116  182]]

Classification Report:
              precision    recall  f1-score   support

     Fiction       0.90      0.91      0.91      1114
  Nonfiction       0.66      0.61      0.63       298

    accuracy                           0.85      1412
   macro avg       0.78      0.76      0.77      1412
weighted avg       0.85      0.85      0.85      1412



In [ ]:
# Logistic Regression with Word2Vec Vectorization method - low precision but tradeoff with recall value

from gensim.models import Word2Vec
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Tokenize sentences into words
tokenized_corpus = [sentence.split() for sentence in corpus]

# Create Word2Vec model
w2v_model = Word2Vec(sentences=tokenized_corpus, vector_size=150, window=3, min_count=1, workers=4)

# Encode labels
label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(labels)

# Check the mapping of original labels to encoded labels
label_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Label Mapping:", label_mapping)

# Generate feature vectors by averaging word vectors for each sentence
feature_vectors = np.array([np.mean([w2v_model.wv[word] for word in sentence if word in w2v_model.wv], axis=0) for sentence in tokenized_corpus])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(feature_vectors, encoded_labels, test_size=0.33, random_state=42)

# Create a logistic regression model
model = LogisticRegression(class_weight='balanced')

# Train the model on the training data
model.fit(X_train, y_train)

# Make predictions on the test data
predictions = model.predict(X_test)

# Decode labels
decoded_predictions = label_encoder.inverse_transform(predictions)

# Evaluate the model
accuracy = accuracy_score(y_test, predictions)
conf_matrix = confusion_matrix(y_test, predictions)
classification_rep = classification_report(y_test, predictions)

# Display the results
print("Accuracy:", accuracy)
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)


Label Mapping: {'Fiction': 0, 'Nonfiction': 1}
Accuracy: 0.6062322946175638

Confusion Matrix:
[[685 429]
 [127 171]]

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.61      0.71      1114
           1       0.28      0.57      0.38       298

    accuracy                           0.61      1412
   macro avg       0.56      0.59      0.55      1412
weighted avg       0.73      0.61      0.64      1412



In [ ]:
# tf-idf with logistic regression

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(corpus, labels, test_size=0.33, random_state=42)

# Create TF-IDF vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fit and transform the training data
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)

# Transform the test data
X_test_tfidf = tfidf_vectorizer.transform(X_test)

# Create a logistic regression model
model = LogisticRegression(class_weight = 'balanced')

# Train the model on the training data
model.fit(X_train_tfidf, y_train)

# Make predictions on the test data
predictions = model.predict(X_test_tfidf)

# Evaluate the model
accuracy = accuracy_score(y_test, predictions)
conf_matrix = confusion_matrix(y_test, predictions)
classification_rep = classification_report(y_test, predictions)

# Display the results
print("Accuracy:", accuracy)
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)


Accuracy: 0.8562322946175638

Confusion Matrix:
[[1008  106]
 [  97  201]]

Classification Report:
              precision    recall  f1-score   support

     Fiction       0.91      0.90      0.91      1114
  Nonfiction       0.65      0.67      0.66       298

    accuracy                           0.86      1412
   macro avg       0.78      0.79      0.79      1412
weighted avg       0.86      0.86      0.86      1412



XGBoost Classification

In [ ]:
!pip install xgboost

In [ ]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# Create the CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the corpus into a bag-of-words matrix
X = vectorizer.fit_transform(corpus).toarray()
feature_names = vectorizer.get_feature_names_out()

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.33, random_state=42)

# Encode class labels using LabelEncoder
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# Check the mapping of original class names to encoded labels
class_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Class Mapping:", class_mapping)

# Calculate class weights to address class imbalance
class_weights = len(y_train_encoded) / (2 * np.bincount(y_train_encoded))

# XGBoost classifier with class weights
# the calculated class weights to the scale_pos_weight parameter of the XGBoost classifier.
# This parameter adjusts the balance between positive and negative classes during training.
model = XGBClassifier(scale_pos_weight=class_weights[1])

# Train the model on the training data
model.fit(X_train, y_train_encoded)

# Make predictions on the test data
predictions = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test_encoded, predictions)
conf_matrix = confusion_matrix(y_test_encoded, predictions)
classification_rep = classification_report(y_test_encoded, predictions)

# Display the results
print("Accuracy:", accuracy)
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)

Class Mapping: {'Fiction': 0, 'Nonfiction': 1}
Accuracy: 0.8569405099150141

Confusion Matrix:
[[1038   76]
 [ 126  172]]

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.93      0.91      1114
           1       0.69      0.58      0.63       298

    accuracy                           0.86      1412
   macro avg       0.79      0.75      0.77      1412
weighted avg       0.85      0.86      0.85      1412



In [ ]:
# XGBoost with Word2Vec

import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from gensim.models import Word2Vec

# Tokenize sentences into words
tokenized_corpus = [sentence.split() for sentence in corpus]

# Create Word2Vec model
w2v_model = Word2Vec(sentences=tokenized_corpus, vector_size=50, window=5, min_count=1, workers=4)

# Generate feature vectors by averaging word vectors for each sentence
feature_vectors = np.array([np.mean([w2v_model.wv[word] for word in sentence if word in w2v_model.wv], axis=0) for sentence in tokenized_corpus])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(feature_vectors, labels, test_size=0.33, random_state=42)

# Encode class labels using LabelEncoder
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# Check the mapping of original class names to encoded labels
class_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Class Mapping:", class_mapping)

# Calculate class weights to address class imbalance
class_weights = len(y_train_encoded) / (2 * np.bincount(y_train_encoded))

# XGBoost classifier with adjusted class weights and other hyperparameter tuning
model = XGBClassifier(
    scale_pos_weight=class_weights[1],
    learning_rate=0.1,
    max_depth=10,
    n_estimators=300
)

# Train the model on the training data
model.fit(X_train, y_train_encoded)

# Make predictions on the test data
predictions = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test_encoded, predictions)
conf_matrix = confusion_matrix(y_test_encoded, predictions)
classification_rep = classification_report(y_test_encoded, predictions)

# Display the results
print("Accuracy:", accuracy)
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)


Class Mapping: {'Fiction': 0, 'Nonfiction': 1}
Accuracy: 0.7804532577903682

Confusion Matrix:
[[1033   81]
 [ 229   69]]

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.93      0.87      1114
           1       0.46      0.23      0.31       298

    accuracy                           0.78      1412
   macro avg       0.64      0.58      0.59      1412
weighted avg       0.74      0.78      0.75      1412



In [ ]:
# XGboost with TF-IDF
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# Create the TfidfVectorizer
vectorizer = TfidfVectorizer()

# Fit and transform the corpus into a TF-IDF matrix
X = vectorizer.fit_transform(corpus).toarray()
feature_names = vectorizer.get_feature_names_out()

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.33, random_state=42)

# Encode class labels using LabelEncoder
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# Check the mapping of original class names to encoded labels
class_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Class Mapping:", class_mapping)

# Calculate class weights to address class imbalance
class_weights = len(y_train_encoded) / (2 * np.bincount(y_train_encoded))

# XGBoost classifier with class weights
model = XGBClassifier(scale_pos_weight=class_weights[1])

# Train the model on the training data
model.fit(X_train, y_train_encoded)

# Make predictions on the test data
predictions = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test_encoded, predictions)
conf_matrix = confusion_matrix(y_test_encoded, predictions)
classification_rep = classification_report(y_test_encoded, predictions)

# Display the results
print("Accuracy:", accuracy)
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)


Class Mapping: {'Fiction': 0, 'Nonfiction': 1}
Accuracy: 0.8406515580736544

Confusion Matrix:
[[1029   85]
 [ 140  158]]

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.92      0.90      1114
           1       0.65      0.53      0.58       298

    accuracy                           0.84      1412
   macro avg       0.77      0.73      0.74      1412
weighted avg       0.83      0.84      0.83      1412



Random Forest Classification

In [ ]:
# RF With BOG

import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# Create the CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the corpus into a bag-of-words matrix
X = vectorizer.fit_transform(corpus).toarray()
feature_names = vectorizer.get_feature_names_out()

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.33, random_state=42)

# Encode class labels using LabelEncoder
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# Check the mapping of original class names to encoded labels
class_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Class Mapping:", class_mapping)

# Calculate class weights to address class imbalance
class_weights = len(y_train_encoded) / (2 * np.bincount(y_train_encoded))

# Increase the weight of the nonfiction class
class_weights[1] *= 2.0

# Random Forest classifier with class weights
model = RandomForestClassifier(class_weight={0: 1, 1: class_weights[1]})

# Train the model on the training data
model.fit(X_train, y_train_encoded)

# Make predictions on the test data
predictions = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test_encoded, predictions)
conf_matrix = confusion_matrix(y_test_encoded, predictions)
classification_rep = classification_report(y_test_encoded, predictions)

# Display the results
print("Accuracy:", accuracy)
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)

Class Mapping: {'Fiction': 0, 'Nonfiction': 1}
Accuracy: 0.8548158640226629

Confusion Matrix:
[[1097   17]
 [ 188  110]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.98      0.91      1114
           1       0.87      0.37      0.52       298

    accuracy                           0.85      1412
   macro avg       0.86      0.68      0.72      1412
weighted avg       0.86      0.85      0.83      1412



In [ ]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# Create the CountVectorizer
vectorizer = CountVectorizer()

# Fit and transform the corpus into a bag-of-words matrix
X = vectorizer.fit_transform(corpus).toarray()
feature_names = vectorizer.get_feature_names_out()

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.33, random_state=42)

# Encode class labels using LabelEncoder
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# Check the mapping of original class names to encoded labels
class_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Class Mapping:", class_mapping)

# Calculate class weights to address class imbalance
class_weights = len(y_train_encoded) / (2 * np.bincount(y_train_encoded))

# Increase the weight of the nonfiction class
class_weights[1] *= 2.0

# Random Forest classifier with class weights
model = RandomForestClassifier(class_weight={0: 1, 1: class_weights[1]}, max_depth = 25, n_estimators = 300)

# Train the model on the training data
model.fit(X_train, y_train_encoded)

# Make predictions on the test data
predictions = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test_encoded, predictions)
conf_matrix = confusion_matrix(y_test_encoded, predictions)
classification_rep = classification_report(y_test_encoded, predictions)

# Display the results
print("Accuracy:", accuracy)
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)

Class Mapping: {'Fiction': 0, 'Nonfiction': 1}
Accuracy: 0.7060906515580736

Confusion Matrix:
[[750 364]
 [ 51 247]]

Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.67      0.78      1114
           1       0.40      0.83      0.54       298

    accuracy                           0.71      1412
   macro avg       0.67      0.75      0.66      1412
weighted avg       0.82      0.71      0.73      1412



In [ ]:
# RF with word2vec
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from gensim.models import Word2Vec

# Tokenize sentences into words
tokenized_corpus = [sentence.split() for sentence in corpus]

# Create Word2Vec model
w2v_model = Word2Vec(sentences=tokenized_corpus, vector_size=200, window=5, min_count=1, workers=4)

# Generate feature vectors by averaging word vectors for each sentence
w2v_feature_vectors = np.array([np.mean([w2v_model.wv[word] for word in sentence if word in w2v_model.wv], axis=0) for sentence in tokenized_corpus])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(w2v_feature_vectors, labels, test_size=0.33, random_state=42)

# Encode class labels using LabelEncoder
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# Check the mapping of original class names to encoded labels
class_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Class Mapping:", class_mapping)

# Calculate class weights to address class imbalance
class_weights = len(y_train_encoded) / (2 * np.bincount(y_train_encoded))
class_weights[1] *= 2.0  # Increase the weight of the nonfiction class

# Random Forest classifier with class weights
model = RandomForestClassifier(class_weight={0: 1, 1: class_weights[1]}, max_depth = 8, n_estimators = 300)

# Train the model on the training data
model.fit(X_train, y_train_encoded)

# Make predictions on the test data
predictions = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test_encoded, predictions)
conf_matrix = confusion_matrix(y_test_encoded, predictions)
classification_rep = classification_report(y_test_encoded, predictions)

# Display the results
print("Accuracy:", accuracy)
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)


Class Mapping: {'Fiction': 0, 'Nonfiction': 1}
Accuracy: 0.6735127478753541

Confusion Matrix:
[[839 275]
 [186 112]]

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.75      0.78      1114
           1       0.29      0.38      0.33       298

    accuracy                           0.67      1412
   macro avg       0.55      0.56      0.56      1412
weighted avg       0.71      0.67      0.69      1412



In [ ]:
# RF With TF-IDF
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

# Create the TfidfVectorizer
vectorizer = TfidfVectorizer()

# Fit and transform the corpus into a TF-IDF matrix
tfidf_matrix = vectorizer.fit_transform(corpus).toarray()

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(tfidf_matrix, labels, test_size=0.33, random_state=42)

# Encode class labels using LabelEncoder
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# Check the mapping of original class names to encoded labels
class_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Class Mapping:", class_mapping)

# Calculate class weights to address class imbalance
class_weights = len(y_train_encoded) / (2 * np.bincount(y_train_encoded))
class_weights[1] *= 2.0  # Increase the weight of the nonfiction class

# Random Forest classifier with class weights
model = RandomForestClassifier(class_weight={0: 1, 1: class_weights[1]}, max_depth = 25, n_estimators = 300)

# Train the model on the training data
model.fit(X_train, y_train_encoded)

# Make predictions on the test data
predictions = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test_encoded, predictions)
conf_matrix = confusion_matrix(y_test_encoded, predictions)
classification_rep = classification_report(y_test_encoded, predictions)

# Display the results
print("Accuracy:", accuracy)
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)

Class Mapping: {'Fiction': 0, 'Nonfiction': 1}
Accuracy: 0.7252124645892352

Confusion Matrix:
[[779 335]
 [ 53 245]]

Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.70      0.80      1114
           1       0.42      0.82      0.56       298

    accuracy                           0.73      1412
   macro avg       0.68      0.76      0.68      1412
weighted avg       0.83      0.73      0.75      1412



Naive Bayes Classification

In [ ]:
# NB with BOG
# Hyperparameter tuning with value of alpha, gridsearchcv and smote

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTE

# Create the TfidfVectorizer
vectorizer = TfidfVectorizer()

# Fit and transform the corpus into a TF-IDF matrix
X = vectorizer.fit_transform(corpus).toarray()
feature_names = vectorizer.get_feature_names_out()

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.33, random_state=42)

# Encode class labels using LabelEncoder
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# Check the mapping of original class names to encoded labels
class_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Class Mapping:", class_mapping)

# Oversample the minority class using SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train, y_train_encoded)

# Naive Bayes classifier (Multinomial Naive Bayes) with grid search
param_grid = {'alpha': [0.1, 0.5, 1.0, 1.5, 2.0]}
grid_search = GridSearchCV(MultinomialNB(), param_grid, cv=5, scoring='f1_macro')
grid_search.fit(X_resampled, y_resampled)

# Best parameters from grid search
best_params = grid_search.best_params_
print("Best Parameters:", best_params)

# Train the model on the resampled training data
model = MultinomialNB(alpha=best_params['alpha'])
model.fit(X_resampled, y_resampled)

# Make predictions on the test data
predictions = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test_encoded, predictions)
conf_matrix = confusion_matrix(y_test_encoded, predictions)
classification_rep = classification_report(y_test_encoded, predictions)

# Display the results
print("Accuracy:", accuracy)
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)


Class Mapping: {'Fiction': 0, 'Nonfiction': 1}
Best Parameters: {'alpha': 0.1}
Accuracy: 0.806657223796034

Confusion Matrix:
[[939 175]
 [ 98 200]]

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.84      0.87      1114
           1       0.53      0.67      0.59       298

    accuracy                           0.81      1412
   macro avg       0.72      0.76      0.73      1412
weighted avg       0.83      0.81      0.81      1412



In [ ]:
# NB With Word2Vec

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from gensim.models import Word2Vec
from imblearn.over_sampling import SMOTE

# Tokenize sentences into words
tokenized_corpus = [sentence.split() for sentence in corpus]

# Create Word2Vec model
w2v_model = Word2Vec(sentences=tokenized_corpus, vector_size=200, window=2, min_count=1, workers=4)

# Generate feature vectors by averaging word vectors for each sentence
X = np.array([np.mean([w2v_model.wv[word] for word in sentence if word in w2v_model.wv], axis=0) for sentence in tokenized_corpus])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.33, random_state=42)

# Encode class labels using LabelEncoder
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# Check the mapping of original class names to encoded labels
class_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Class Mapping:", class_mapping)

# Oversample the minority class using SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train, y_train_encoded)

# Gaussian Naive Bayes classifier
model = GaussianNB()

# Train the model on the resampled training data
model.fit(X_resampled, y_resampled)

# Make predictions on the test data
predictions = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test_encoded, predictions)
conf_matrix = confusion_matrix(y_test_encoded, predictions)
classification_rep = classification_report(y_test_encoded, predictions)

# Display the results
print("Accuracy:", accuracy)
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)

Class Mapping: {'Fiction': 0, 'Nonfiction': 1}
Accuracy: 0.7117563739376771

Confusion Matrix:
[[965 149]
 [258  40]]

Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.87      0.83      1114
           1       0.21      0.13      0.16       298

    accuracy                           0.71      1412
   macro avg       0.50      0.50      0.50      1412
weighted avg       0.67      0.71      0.69      1412



In [ ]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from imblearn.over_sampling import SMOTE

# Create the TfidfVectorizer
vectorizer = TfidfVectorizer()

# Fit and transform the corpus into a TF-IDF matrix
X = vectorizer.fit_transform(corpus).toarray()
feature_names = vectorizer.get_feature_names_out()

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.33, random_state=42)

# Encode class labels using LabelEncoder
label_encoder = LabelEncoder()
y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# Check the mapping of original class names to encoded labels
class_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print("Class Mapping:", class_mapping)

# Oversample the minority class using SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_train, y_train_encoded)

# Naive Bayes classifier (Multinomial Naive Bayes) with grid search
param_grid = {'alpha': [0.1, 0.5, 1.0, 1.5, 2.0]}
grid_search = GridSearchCV(MultinomialNB(), param_grid, cv=5, scoring='f1_macro')
grid_search.fit(X_resampled, y_resampled)

# Best parameters from grid search
best_params = grid_search.best_params_
print("Best Parameters:", best_params)

# Train the model on the resampled training data
model = MultinomialNB(alpha=best_params['alpha'])
model.fit(X_resampled, y_resampled)

# Make predictions on the test data
predictions = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test_encoded, predictions)
conf_matrix = confusion_matrix(y_test_encoded, predictions)
classification_rep = classification_report(y_test_encoded, predictions)

# Display the results
print("Accuracy:", accuracy)
print("\nConfusion Matrix:")
print(conf_matrix)
print("\nClassification Report:")
print(classification_rep)

Class Mapping: {'Fiction': 0, 'Nonfiction': 1}
Best Parameters: {'alpha': 0.1}
Accuracy: 0.806657223796034

Confusion Matrix:
[[939 175]
 [ 98 200]]

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.84      0.87      1114
           1       0.53      0.67      0.59       298

    accuracy                           0.81      1412
   macro avg       0.72      0.76      0.73      1412
weighted avg       0.83      0.81      0.81      1412



In [ ]:
count1 = 0
count2 = 0
for word in labels:
  if word == 'Fiction':
    count1+=1
  elif word == 'Nonfiction':
    count2+=1
print(count1)
count2

3417


860